### ISSUE TITLE
ConvertVCF2MVF

### ISSUE THREAD

**Issue by ceposadap** [jbpease/mvftools#5]
Hi James,

I've been trying to use mvftools to create input files for d-foil. I have a vcf file that cointains all taxa that I wish to analyze, but when I try to convert it from the vcf to the mvf format it throws an error:

Traceback (most recent call last):
  File "data/scripts/mvftools-master/mvftools.py", line 901, in <module>
    MVFcall()
  File "data/scripts/mvftools-master/mvftools.py", line 88, in __init__
    getattr(self, args.command)()
  File "data/scripts/mvftools-master/mvftools.py", line 384, in ConvertVCF2MVF
    vcf2mvf(args)
  File "/datacnmat01/biologia/biologia.evolutiva/carlos.posada/scripts/mvftools-master/pylib/mvfvcf.py", line 383, in vcf2mvf
    for vcfrecord in vcf.iterentries(args):
  File "/datacnmat01/biologia/biologia.evolutiva/carlos.posada/scripts/mvftools-master/pylib/mvfvcf.py", line 148, in iterentries
    vcfrecord = self._parse_entry(xline, **vars(args))
  File "/datacnmat01/biologia/biologia.evolutiva/carlos.posada/scripts/mvftools-master/pylib/mvfvcf.py", line 207, in _parse_entry
    **kwargs))
  File "/datacnmat01/biologia/biologia.evolutiva/carlos.posada/scripts/mvftools-master/pylib/mvfvcf.py", line 283, in _call_allele
    [alleles[x] for x in MLIB.vcf_gtcodes[imaxpl]])])
KeyError: 'T*'

Do you know what's going on? My input file was produced with bcftools merge, which combined vcfs which were themselves genotyped with GATK's GenotypeGVCFs.

Thank you.

Carlos

**Comment by jbpease** [comment]
Hi @ceposadap,

This VCF file includes some non-standard VCF characters inserted by GATK.  Specifically, the use of "*" in the ALT field to signify a deletion state when there are multiple alternative alleles (as opposed to a standard INDEL entry).  I have modified the behavior of the converter to accept these entries.  Note that hemizygous deletion calls "A/*" will be converted to "A", while heterozygous deletion calls "*/*" will register as a "-".  Poor quality calls that are masked in the hemizygous base (i.e., "N/*") should still convert to "X" for the MVF format.

The test file you provided converted on my machine with the new version (0.5.3.1b).
James
