### ISSUE TITLE
Can run at Python 2.7 but not for Python 3.x

### ISSUE THREAD

**Issue by yzongzjnu** [jbpease/mvftools#7]
I can run mvftools at Python 2.7 but not for Python 3.5. So I am confused by your instruction in README.md. Beside, if mvftools need BioPython modules, please clarify that.  Thanks!
```
python3 mvftools.py ConvertVCF2MVF --vcf Chloroplast_CallVariants.vcf --mvf Chloroplast_CallVariants.mvf
Traceback (most recent call last):
  File "mvftools.py", line 18, in <module>
    from pylib.mvfwindowtree import infer_window_tree
  File "/mnt/c/Ubuntu/mvftools/pylib/mvfwindowtree.py", line 39, in <module>
    from Bio import Phylo
ImportError: No module named 'Bio'
```
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'Bio'
>>> import Bio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'Bio'
>>> exit()
```
```
 python2.7 mvftools.py
usage: Choose from the following commands:
            AnnotateMVF
            CalcCharacterCount
            CalcDstatCombinations
            CalcPairwiseDistances
            CalcPatternCount
            CalcSampleCoverage
            CheckMVF
            ConvertFasta2MVF
            ConvertMAF2MVF
            ConvertMVF2Fasta
            ConvertMVF2Phylip
            ConvertVCF2MVF
            FilterMVF
            InferGroupSpecificAllele
            InferTree
            PlotChromoplot
            TranslateMVF
```
OS Bash on Ubuntu on Window10

**Comment by jbpease** [comment]
Sorry for the delay.   I have corrected disparities between the manual and the README and attempted to clarify both.  Thanks for your question.
