### ISSUE TITLE
Hello ,here is some trouble using  MVFtools and dfoil.

### ISSUE THREAD

**Issue by SkyStarStear** [jbpease/mvftools#9]
Hello,
     When I use dfoil, the test2 file can be successfully tested, but when running test.fa and my own sequence, it will report an error at runtime, as follows:
###  python  ../test/run_test.py ../test/test.fa
Running  ../fasta2dfoil.py ../test/test.fa -o ../test/test.fa.counts --names P1,P2,P3,P4,PO
Running  ../dfoil.py --infile ../test/test.fa.counts --out ../test/test.fa.dfoil --mode dfoil --plot ../test/test.fa.dfoil.pdf
Running pre-check on ../test/test.fa.counts
Traceback (most recent call last):
  File "../dfoil.py", line 689, in <module>
    main()
  File "../dfoil.py", line 684, in main
    window_data, bool_data)
  File "../dfoil.py", line 369, in plot_dfoil
    for x in range(2, len(bool_data[0]))]
IndexError: list index out of range
 
  When I tried to use the CalcPatternCount function of MVFtools to try to convert my VCF format snp information into dfoil input file, it took up a lot of memory (600gb) and eventually the memory overflowed（about 20,000 snp sites and 200 samples）.
   I have snp information for three sets of genomes of plants, around 200000 (nuclear genome) and 800 (mitochondrial and chloroplast genomes). I want to specifically study the difference in gene penetration between the three sets of genomes. Through the literature, I found that dfoil is a very good software, I hope to get rich data through this software, the following is my data.

Dear，
Zhe
[all.zip](https://github.com/jbpease/mvftools/files/3421823/all.zip)

**Comment by SkyStarStear** [comment]
Has taken up 400g of memory and is still increasing for only 800 sites,I don't know what happened .
